/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mitre_giscore_filegdb_Geodatabase */

#ifndef _Included_org_mitre_giscore_filegdb_Geodatabase
#define _Included_org_mitre_giscore_filegdb_Geodatabase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getChildDatasets
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getChildDatasets
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getDatasetTypes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getDatasetTypes
  (JNIEnv *, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getRelatedDatasets
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getRelatedDatasets
  (JNIEnv *, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getDatasetDef
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getDatasetDef
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getDatasetDocumentation
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getDatasetDocumentation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    close_db
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_close_1db
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
