/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mitre_giscore_filegdb_EnumRows */

#ifndef _Included_org_mitre_giscore_filegdb_EnumRows
#define _Included_org_mitre_giscore_filegdb_EnumRows
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: NULL_OBJECT */
/*
 * Class:     org_mitre_giscore_filegdb_EnumRows
 * Method:    next1
 * Signature: ()Lorg/mitre/giscore/filegdb/Row;
 */
JNIEXPORT jobject JNICALL Java_org_mitre_giscore_filegdb_EnumRows_next1
  (JNIEnv *, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_EnumRows
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_EnumRows_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
