/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mitre_giscore_filegdb_Table */

#ifndef _Included_org_mitre_giscore_filegdb_Table
#define _Included_org_mitre_giscore_filegdb_Table
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mitre_giscore_filegdb_Table
 * Method:    add
 * Signature: (Lorg/mitre/giscore/filegdb/Row;)V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Table_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_Table
 * Method:    enumerate1
 * Signature: ()Lorg/mitre/giscore/filegdb/EnumRows;
 */
JNIEXPORT jobject JNICALL Java_org_mitre_giscore_filegdb_Table_enumerate1
  (JNIEnv *, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_Table
 * Method:    getFieldInfo
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_mitre_giscore_filegdb_Table_getFieldInfo
  (JNIEnv *, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_Table
 * Method:    initRow
 * Signature: (Lorg/mitre/giscore/filegdb/Row;)V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Table_initRow
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_Table
 * Method:    close1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Table_close1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
