/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mitre_giscore_filegdb_Geodatabase */

#ifndef _Included_org_mitre_giscore_filegdb_Geodatabase
#define _Included_org_mitre_giscore_filegdb_Geodatabase
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: NULL_OBJECT */
/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    closeAndDestroy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_closeAndDestroy
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    test
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_test
  (JNIEnv *, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getDatasetTypes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getDatasetTypes
  (JNIEnv *, jobject);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getDatasetDefinition
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getDatasetDefinition
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getChildDatasets
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getChildDatasets
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    getChildDatasetDefinitions
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_getChildDatasetDefinitions
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    createFeatureDataset
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_createFeatureDataset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    openTable
 * Signature: (Ljava/lang/String;)Lorg/mitre/giscore/filegdb/Table;
 */
JNIEXPORT jobject JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_openTable
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    createTable
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lorg/mitre/giscore/filegdb/Table;
 */
JNIEXPORT jobject JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_createTable
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_mitre_giscore_filegdb_Geodatabase
 * Method:    closeTable
 * Signature: (Lorg/mitre/giscore/filegdb/Table;)V
 */
JNIEXPORT void JNICALL Java_org_mitre_giscore_filegdb_Geodatabase_closeTable
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
