/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensextant_giscore_filegdb_Row */

#ifndef _Included_org_opensextant_giscore_filegdb_Row
#define _Included_org_opensextant_giscore_filegdb_Row
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensextant_giscore_filegdb_Row
 * Method:    getOID
 * Signature: ()Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_org_opensextant_giscore_filegdb_Row_getOID
  (JNIEnv *, jobject);

/*
 * Class:     org_opensextant_giscore_filegdb_Row
 * Method:    getGeo
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_opensextant_giscore_filegdb_Row_getGeo
  (JNIEnv *, jobject);

/*
 * Class:     org_opensextant_giscore_filegdb_Row
 * Method:    setGeometry
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_opensextant_giscore_filegdb_Row_setGeometry
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_opensextant_giscore_filegdb_Row
 * Method:    getAttrArray
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_opensextant_giscore_filegdb_Row_getAttrArray
  (JNIEnv *, jobject);

/*
 * Class:     org_opensextant_giscore_filegdb_Row
 * Method:    setAttrArray
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_opensextant_giscore_filegdb_Row_setAttrArray
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
