/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensextant_giscore_filegdb_Table_FieldInfo */

#ifndef _Included_org_opensextant_giscore_filegdb_Table_FieldInfo
#define _Included_org_opensextant_giscore_filegdb_Table_FieldInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
